using System.Collections.Generic;

namespace APITest
{
    public class DummyData
    {
        public static double?[] Data1 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 4.9, (double?)null, (double?)null, (double?)null, (double?)null, 8.6, (double?)null, 3.2, 7.2, 14.6, (double?)null, (double?)null, 5.1, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data2 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 6.8, (double?)null, (double?)null, (double?)null, (double?)null, 6.8, (double?)null, 7, 3, (double?)null, 5.2, 3.8, 7.1, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data3 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 5.2, (double?)null, (double?)null, 4, 5.9, 13.9, (double?)null, (double?)null, (double?)null, (double?)null, 7.2, 3.4, (double?)null, 10.6, (double?)null, (double?)null, (double?)null };
        public static double?[] Data4 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 5.9, (double?)null, (double?)null, (double?)null, (double?)null, 4.3, 5.9, 6.9, 6.1, 5.9, (double?)null, (double?)null, 3.7, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data5 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 5.7, (double?)null, (double?)null, (double?)null, (double?)null, 9.9, (double?)null, (double?)null, (double?)null, 12.3, (double?)null, (double?)null, 6.8, 3.6, (double?)null, (double?)null, (double?)null };
        public static double?[] Data6 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 4.8, (double?)null, 5.7, 3.1, 8.8, 7.7, (double?)null, (double?)null, (double?)null, 6.1, (double?)null, 11, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data7 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 3.8, 3.4, 2.6, 6.1, (double?)null, (double?)null, (double?)null, (double?)null, 14.2, 4, 3.2, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data8 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 3.7, 6.3, (double?)null, (double?)null, 8.9, (double?)null, (double?)null, (double?)null, (double?)null, 9.8, 4.4, 2.7, 5.5, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data9 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 5.6, (double?)null, (double?)null, (double?)null, (double?)null, 10.6, (double?)null, (double?)null, (double?)null, 3.1, 6.7, 4.4, 6.2, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data10 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 4.5, (double?)null, (double?)null, (double?)null, (double?)null, 6.5, (double?)null, (double?)null, (double?)null, (double?)null, 3.8, 6.9, (double?)null, 12, 13, (double?)null, (double?)null };
        public static double?[] Data11 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 3.9, (double?)null, (double?)null, (double?)null, 5.8, 3.6, (double?)null, (double?)null, 6.2, 6.7, (double?)null, 5.2, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data11_2 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 6.5, (double?)null, (double?)null, (double?)null, (double?)null, 5, (double?)null, (double?)null, (double?)null, 7.9, (double?)null, 5.3, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data11_3 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 6.2, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data12 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 3.6, (double?)null, (double?)null, (double?)null, 6.8, (double?)null, (double?)null, (double?)null, 6.3, 3.7, (double?)null, 9, 3.1, 6.4, (double?)null, (double?)null };
        public static double?[] Data12_2 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 12.2, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 4.8, (double?)null, 8.7, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data13 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 4.9, (double?)null, (double?)null, 4.5, (double?)null, (double?)null, 7.8, (double?)null, 12.3, 6.4, 3.6, (double?)null, 4.7, 4.5, (double?)null, (double?)null };
        public static double?[] Data14 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 3.8, (double?)null, (double?)null, (double?)null, 4.8, (double?)null, 4.8, (double?)null, 6.7, 3.4, (double?)null, 8.4, (double?)null, 11.6, (double?)null, (double?)null };
        public static double?[] Data14_2 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 5.8, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data15 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 3.5, 10, (double?)null, (double?)null, (double?)null, 8.6, (double?)null, (double?)null, (double?)null, 5.5, 5.5, 5.2, 4.6, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data15_2 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 5.2, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data16 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 3.8, 10.1, (double?)null, 3.8, 10.4, 13.7, (double?)null, 3.7, (double?)null, (double?)null, 4.3, (double?)null, (double?)null, 10.2, (double?)null, (double?)null, (double?)null };
        public static double?[] Data17 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 5.4, (double?)null, (double?)null, (double?)null, 10.3, (double?)null, (double?)null, 3.8, (double?)null, 7.2, 3.9, (double?)null, 8.9, (double?)null, (double?)null, (double?)null };
        public static double?[] Data18 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 4.1, (double?)null, (double?)null, (double?)null, (double?)null, 11.1, 4.4, (double?)null, (double?)null, (double?)null, 3.8, 4.7, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data18_2 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 5.3, (double?)null, (double?)null, (double?)null, 5.3, 6.9, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data18_3 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 2.9, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data19 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 4.4, (double?)null, (double?)null, (double?)null, 8.2, (double?)null, (double?)null, (double?)null, 8.9, 4.8, 6.4, (double?)null, (double?)null, 4.2, (double?)null, (double?)null };
        public static double?[] Data20 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 5.2, (double?)null, (double?)null, (double?)null, 7.1, (double?)null, 3.1, (double?)null, 5.4, (double?)null, (double?)null, (double?)null, 6.2, (double?)null, (double?)null, (double?)null };
        public static double?[] Data21 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 4.7, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 9.8, (double?)null, 5.7, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data22 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 5.9, (double?)null, (double?)null, (double?)null, (double?)null, 9.1, (double?)null, (double?)null, (double?)null, (double?)null, 10.1, 3.4, 6.8, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data23 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 6.1, (double?)null, (double?)null, (double?)null, (double?)null, 9.6, (double?)null, (double?)null, (double?)null, (double?)null, 3.7, (double?)null, 10.4, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data24 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 6.3, (double?)null, (double?)null, (double?)null, 4.1, 16.2, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 8.1, 5.1, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data25 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 6.4, (double?)null, (double?)null, (double?)null, (double?)null, 8.5, (double?)null, (double?)null, (double?)null, (double?)null, 10.2, (double?)null, 7.3, (double?)null, 7.7, (double?)null, (double?)null };
        public static double?[] Data26 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 6.3, 3.6, (double?)null, (double?)null, (double?)null, 8.7, (double?)null, (double?)null, (double?)null, 12.7, (double?)null, 6.7, 3.9, (double?)null, 5.8, (double?)null, (double?)null };
        public static double?[] Data27 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 5.3, (double?)null, (double?)null, (double?)null, 3.6, 4.7, 5.1, 3.5, (double?)null, 10.4, (double?)null, (double?)null, 9.8, (double?)null, (double?)null, (double?)null };
        public static double?[] Data28 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 4.5, (double?)null, 4.1, (double?)null, (double?)null, (double?)null, 8.2, (double?)null, (double?)null, 10.2, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data29 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 3.8, 9.4, (double?)null, (double?)null, (double?)null, 8, (double?)null, (double?)null, (double?)null, 6.4, (double?)null, (double?)null, 5.8, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data30 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 3.2, 9.2, (double?)null, (double?)null, (double?)null, 8.6, (double?)null, (double?)null, (double?)null, 5.1, 3.7, 3.4, 7.9, (double?)null, (double?)null, (double?)null, (double?)null };
        public static double?[] Data31 = new[] { (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, (double?)null, 7.1, (double?)null, (double?)null, (double?)null, (double?)null, 9.1, (double?)null, (double?)null, (double?)null, (double?)null, 10.1, 10.3, (double?)null, 5.7, (double?)null, (double?)null, (double?)null };
        public static List<double?[]> Datas = new List<double?[]> { Data1, Data2, Data3, Data4, Data5, Data6, Data7, Data8, Data9, Data10, Data11, Data11_2, Data11_3, Data12, Data12_2, Data13, Data14, Data14_2, Data15, Data15_2, Data16, Data17, Data18, Data18_2, Data18_3, Data19, Data20, Data21, Data22, Data23, Data24, Data25, Data26, Data27, Data28, Data29, Data30, Data31 };

    }
}
